.TH "AudioManager" 3 "Sun May 5 2019" "The Great Adventure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AudioManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPlaySFX\fP (int soundToPlay)"
.br
.ti -1c
.RI "void \fBPlayBGM\fP (int musicToPlay)"
.br
.ti -1c
.RI "void \fBStopMusic\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AudioSource [] \fBsfx\fP"
.br
.ti -1c
.RI "AudioSource [] \fBbgm\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBAudioManager\fP \fBinstance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for The Great Adventure from the source code\&.
