.TH "BattleMove" 3 "Sun May 5 2019" "The Great Adventure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleMove
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBmoveName\fP"
.br
.ti -1c
.RI "int \fBmovePower\fP"
.br
.ti -1c
.RI "int \fBmoveCost\fP"
.br
.ti -1c
.RI "\fBAttackEffect\fP \fBtheEffect\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for The Great Adventure from the source code\&.
