.TH "BattleChar" 3 "Sun May 5 2019" "The Great Adventure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BattleChar
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEnemyFade\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBisPlayer\fP"
.br
.ti -1c
.RI "string [] \fBmovesAvailable\fP"
.br
.ti -1c
.RI "string \fBcharName\fP"
.br
.ti -1c
.RI "int \fBcurrentHP\fP"
.br
.ti -1c
.RI "bool \fBhasDied\fP"
.br
.ti -1c
.RI "SpriteRenderer \fBtheSprite\fP"
.br
.ti -1c
.RI "Sprite \fBdeadSprite\fP"
.br
.ti -1c
.RI "float \fBfadeSpeed\fP = 1f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for The Great Adventure from the source code\&.
