.TH "DamageNumber" 3 "Sun May 5 2019" "The Great Adventure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DamageNumber
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetDamage\fP (int damageAmount)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Text \fBdamageText\fP"
.br
.ti -1c
.RI "float \fBlifetime\fP = 1f"
.br
.ti -1c
.RI "float \fBmoveSpeed\fP = 1f"
.br
.ti -1c
.RI "float \fBplacementJitter\fP = \&.5f"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for The Great Adventure from the source code\&.
