.TH "ItemButton" 3 "Sun May 5 2019" "The Great Adventure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ItemButton
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPress\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Image \fBButtonImage\fP"
.br
.ti -1c
.RI "Text \fBamountText\fP"
.br
.ti -1c
.RI "int \fBbuttonValue\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for The Great Adventure from the source code\&.
