.TH "QuestMarker" 3 "Sun May 5 2019" "The Great Adventure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
QuestMarker
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMarkQuest\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "string \fBquestToMark\fP"
.br
.ti -1c
.RI "bool \fBmarkComplete\fP"
.br
.ti -1c
.RI "bool \fBmarkOnEnter\fP"
.br
.ti -1c
.RI "bool \fBdeactivateOnMarking\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for The Great Adventure from the source code\&.
