.TH "Shop" 3 "Sun May 5 2019" "The Great Adventure" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Shop
.SH SYNOPSIS
.br
.PP
.PP
Inherits MonoBehaviour\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBOpenShop\fP ()"
.br
.ti -1c
.RI "void \fBCloseShop\fP ()"
.br
.ti -1c
.RI "void \fBOpenBuyMenu\fP ()"
.br
.ti -1c
.RI "void \fBOpenSellMenu\fP ()"
.br
.ti -1c
.RI "void \fBSelectBuyItem\fP (\fBItem\fP selectedItem)"
.br
.ti -1c
.RI "void \fBSelectSellItem\fP (\fBItem\fP sellItem)"
.br
.ti -1c
.RI "void \fBBuyItem\fP ()"
.br
.ti -1c
.RI "void \fBSellItem\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "GameObject \fBshopMenu\fP"
.br
.ti -1c
.RI "GameObject \fBbuyMenu\fP"
.br
.ti -1c
.RI "GameObject \fBsellMenu\fP"
.br
.ti -1c
.RI "Text \fBgoldText\fP"
.br
.ti -1c
.RI "string [] \fBitemsForSale\fP"
.br
.ti -1c
.RI "\fBItemButton\fP [] \fBbuyItemButtons\fP"
.br
.ti -1c
.RI "\fBItemButton\fP [] \fBsellItemButtons\fP"
.br
.ti -1c
.RI "\fBItem\fP \fBselectedItem\fP"
.br
.ti -1c
.RI "Text \fBbuyItemName\fP"
.br
.ti -1c
.RI "Text \fBsellItemName\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static \fBShop\fP \fBinstance\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for The Great Adventure from the source code\&.
